apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: delta27222/nnotes_backend:latest
        ports:
        - containerPort: 3001
          name: backendport
        env:
        - name: DB_URI
          value: "mongodb://mongodb-service:27017/"
        - name: PORT
          value: "3001"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  clusterIP: 10.152.183.100
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: backendport