name: Integration Test CI
run-name: Integration Test CI - Microk8s

# Solo se ejecuta desde el workflow de Docker Image CI
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    # Creo que el if no es necesario, ya que si el test del workflow anterior falla, este no se ejecuta
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install microk8s
        run: |
          sudo snap install microk8s --channel 1.29-strict/stable
      # - name: Wait
      #   run: sleep 15
      - name: Change permissions
        run: |
          sudo microk8s status --wait-ready
          GROUP=snap_microk8s # microk8s for non-strict
          sudo usermod -a -G $GROUP $USER
          newgrp $GROUP
          mkdir ~/.kube
          sudo chown -f -R $USER ~/.kube
      # no funciona agregar el usuario al grupo porque debemos reiniciar la sesión, asi que usamos sudo
      - name: Enable addons
        run: |
          sudo microk8s enable hostpath-storage
          sudo microk8s enable dns
      - name: Change microk8s config
        run: |
          sudo sysctl -w fs.inotify.max_user_instances=1280 | sudo tee /etc/sysctl.d/microk8s.conf
          sudo sysctl -w fs.inotify.max_user_watches=655360 | sudo tee -a /etc/sysctl.d/microk8s.conf
      - name: Create alias
        run: |
          alias kubectl="microk8s.kubectl"
          sudo kubectl version

        # ------ la parte de microk8s ------